### ISSUE TITLE
hi contribution to this architecture

### ISSUE THREAD

**Issue by Emma20102** [baldassarreFe/pytorch-densenet-tiramisu#1]
Hi 
I am working on this model and its preform fine for me. I would like to ask if there is any contribution that I can make to this architecture to improve its performance?Many thanks.
Regards,

**Comment by baldassarreFe** [comment]
Hi, thanks for the feedback!

I think the main contribution to this project would be to train one of the predefined architectures on ImageNet and make the weights available. That, of course, requires quite a lot of computing power, that's why I haven't done it yet.

Performance-wise I don't have any improvement in mind, but if you're experimenting with the modules and notice anything that could be added/improved please leave a comment here and we can give it a look.

Btw, which versions of python and pytorch are you using? Are you using one of the predefined architectures or are you assembling the smaller blocks to build your own?
